language: node_js
node_js:
  - "8"
install:
  - cd frontend
  - yarn install
script:
  - yarn test
  - |
    if [ "$TRAVIS_BRANCH" == 'production' ]
    then
      echo "$PUBLIC_KEY";
      echo "$PRIVATE_KEY" > "$PWD/key";
      chmod 600 id_rsa;
      ssh -i "$PWD/key" -oStrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER 'bash deploy_radiodiodi2018.sh';
    fi
