language: node_js
node_js:
  - "8"
install:
  - cd frontend
  - yarn install
script:
  - yarn test
  - |
    if ["$TRAVIS_BRANCH" == 'production' ]
    then
      ssh-add - <<< "$PRIVATE_KEY";
      ssh $DEPLOY_USER@$DEPLOY_SERVER 'bash deploy_radiodiodi2018.sh';
    fi
