language: node_js
node_js:
    - "8"
install:
    - cd frontend
    - yarn install
script:
    - yarn test
    - "$TRAVIS_BRANCH" == 'production' && ssh-add - <<< "$PRIVATE_KEY" && ssh $DEPLOY_USER@$DEPLOY_SERVER 'bash deploy_radiodiodi2018.sh'
