language: node_js
node_js:
  - "8"
install:
  - cd frontend
  - yarn install
script:
  - yarn test
  - |
    if [ "$TRAVIS_BRANCH" == 'production' ]
    then
      echo "$PRIVATE_KEY" > id_rsa;
      ssh -i id_rsa -oStrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER 'bash deploy_radiodiodi2018.sh';
    fi
