language: node_js
node_js:
  - '8'
install:
  - pushd frontend
  - yarn install
  - popd
script:
  - pushd frontend
  - yarn test
  - popd
before_deploy:
  - openssl aes-256-cbc -K $encrypted_18d0203649e0_key -iv $encrypted_18d0203649e0_iv
    -in "$PWD/deploy_key.enc" -out /tmp/deploy_key -d
deploy:
  provider: script
  script:
    - chmod 600 /tmp/deploy_key
    - ssh -i /tmp/deploy_key "$DEPLOY_USER@$DEPLOY_SERVER" 'bash deploy_radiodiodi2018.sh';
  on:
    branch: production
