language: node_js
node_js:
  - '8'
install:
  - cd frontend
  - yarn install
script:
  - yarn test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_18d0203649e0_key -iv $encrypted_18d0203649e0_iv
    -in key.enc -out key -d
deploy:
  provider: script
  script:
    - eval "$(ssh-agent -s)"
    - ssh-add key
    - ssh "$DEPLOY_USER@$DEPLOY_SERVER" 'bash deploy_radiodiodi2018.sh';
  on:
    branch: production
