language: node_js
node_js:
  - "8"
install:
  - cd frontend
  - yarn install
script:
  - yarn test
  - |
    if [ "$TRAVIS_BRANCH" == 'production' ]
    then
      if [ -z "$PRIVATE_KEY" ]
      then
        echo "PRIVATE_KEY is not set!";
        exit 1;
      fi

      echo "$PRIVATE_KEY" > "$PWD/key";
      chmod 600 "$PWD/key";
      eval "$(ssh-agent -s)";
      ssh-add "$PWD/key";
      ssh -oStrictHostKeyChecking=no -oBatchMode=yes $DEPLOY_USER@$DEPLOY_SERVER 'bash deploy_radiodiodi2018.sh';
    fi
